[package]
name = "bevy_mod_schedules"
version = "0.13.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vonforum/bevy_mod_schedules"
description = "A Bevy plugin for expanding the use of schedules."
keywords = ["bevy", "schedules", "plugin", "ecs"]
categories = ["game-development", "game-engines"]
readme = "README.md"

[features]
default = ["app_ext", "nesting"]
app_ext = ["dep:bevy_app"]
nesting = []

[dependencies]
bevy_app = { version = "0.13.0", default-features = false, optional = true }
bevy_ecs = { version = "0.13.0", default-features = false }
bevy_utils = { version = "0.13.0", default-features = false }

[[example]]
name = "nested_schedules"
path = "examples/nested_schedules.rs"
required-features = ["nesting"]
